[25-Nov-2019 22:43:06 PRC] PHP Fatal error:  Cannot use Illuminate\Validation\ValidationException as ValidationException because the name is already in use in F:\zufang\www.fang.com\app\Exceptions\Handler.php on line 8
[25-Nov-2019 22:43:06 PRC] PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php:779
Stack trace:
#0 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(779): ReflectionClass->__construct('App\\Exceptions\\...')
#1 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(658): Illuminate\Container\Container->build('App\\Exceptions\\...')
#2 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(609): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array)
#3 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(735): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(264): Illuminate\Foundation\Application->make('App\\Exceptions\\...', Array)
#5 F:\zufang\www.fang.com\vendor\la in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 779
[25-Nov-2019 22:43:37 PRC] PHP Fatal error:  Cannot use Illuminate\Validation\ValidationException as ValidationException because the name is already in use in F:\zufang\www.fang.com\app\Exceptions\Handler.php on line 8
[25-Nov-2019 22:43:37 PRC] PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php:779
Stack trace:
#0 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(779): ReflectionClass->__construct('App\\Exceptions\\...')
#1 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(658): Illuminate\Container\Container->build('App\\Exceptions\\...')
#2 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(609): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array)
#3 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(735): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(264): Illuminate\Foundation\Application->make('App\\Exceptions\\...', Array)
#5 F:\zufang\www.fang.com\vendor\la in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 779
[25-Nov-2019 22:45:27 PRC] PHP Fatal error:  Cannot use Illuminate\Validation\ValidationException as ValidationException because the name is already in use in F:\zufang\www.fang.com\app\Exceptions\Handler.php on line 8
[25-Nov-2019 22:45:27 PRC] PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php:779
Stack trace:
#0 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(779): ReflectionClass->__construct('App\\Exceptions\\...')
#1 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(658): Illuminate\Container\Container->build('App\\Exceptions\\...')
#2 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(609): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array)
#3 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(735): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(264): Illuminate\Foundation\Application->make('App\\Exceptions\\...', Array)
#5 F:\zufang\www.fang.com\vendor\la in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 779
[25-Nov-2019 22:45:58 PRC] PHP Fatal error:  Cannot use Illuminate\Validation\ValidationException as ValidationException because the name is already in use in F:\zufang\www.fang.com\app\Exceptions\Handler.php on line 8
[25-Nov-2019 22:45:58 PRC] PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php:779
Stack trace:
#0 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(779): ReflectionClass->__construct('App\\Exceptions\\...')
#1 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(658): Illuminate\Container\Container->build('App\\Exceptions\\...')
#2 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(609): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array)
#3 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(735): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(264): Illuminate\Foundation\Application->make('App\\Exceptions\\...', Array)
#5 F:\zufang\www.fang.com\vendor\la in F:\zufang\www.fang.com\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 779
